{application,tcp_metrics,
             [{description,"tcp_metrics monitor"},
              {vsn,"0.1.0"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {env,[]},
              {mod,{tcp_metrics_app,[]}},
              {maintainers,[]},
              {licenses,[]},
              {links,[]},
              {modules,[tcp_metrics_app,tcp_metrics_monitor,
                        tcp_metrics_sup]}]}.
