FROM erlang:19.2

RUN apt-get update
RUN add-apt-repository ppa:chris-lea/libsodium
RUN echo "deb http://ppa.launchpad.net/chris-lea/libsodium/ubuntu trusty main" >> /etc/apt/sources.list
RUN echo "deb-src http://ppa.launchpad.net/chris-lea/libsodium/ubuntu trusty main" >> /etc/apt/sources.list
RUN apt-get install -y libsodium-dev
RUN apt-get install -y openssl
Run apt-get install -y libncurses5-dev libncursesw5-dev

# All roles assumed for dev and testing

CMD /bin/bash
