{application,ip_vs_conn,
             [{description,"/proc/net/ip_vs_conn monitor"},
              {vsn,"0.1.0"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {env,[]},
              {mod,{ip_vs_conn_app,[]}},
              {maintainers,[]},
              {licenses,[]},
              {links,[]},
              {modules,[ip_vs_conn,ip_vs_conn_app,ip_vs_conn_config,
                        ip_vs_conn_map,ip_vs_conn_monitor,ip_vs_conn_sup]}]}.
