%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 3.27.3

-ifndef(mesos_state_overlay_pb).
-define(mesos_state_overlay_pb, true).

-define(mesos_state_overlay_pb_gpb_version, "3.27.3").

-ifndef('MESOS_STATE_OVERLAYINFO_PB_H').
-define('MESOS_STATE_OVERLAYINFO_PB_H', true).
-record(mesos_state_overlayinfo,
        {name                   :: binary() | iolist(), % = 1
         subnet                 :: binary() | iolist(), % = 2
         prefix                 :: non_neg_integer() % = 3, 32 bits
        }).
-endif.

-ifndef('MESOS_STATE_NETWORKCONFIG_PB_H').
-define('MESOS_STATE_NETWORKCONFIG_PB_H', true).
-record(mesos_state_networkconfig,
        {vtep_subnet            :: binary() | iolist(), % = 1
         vtep_mac_oui           :: binary() | iolist(), % = 2
         overlays = []          :: [#mesos_state_overlayinfo{}] % = 3
        }).
-endif.

-ifndef('MESOS_STATE_AGENTOVERLAYINFO.STATE_PB_H').
-define('MESOS_STATE_AGENTOVERLAYINFO.STATE_PB_H', true).
-record('mesos_state_agentoverlayinfo.state',
        {status = 'STATUS_INVALID' :: 'STATUS_INVALID' | 'STATUS_OK' | 'STATUS_FAILED' | 'STATUS_CONFIGURING' | integer() | undefined, % = 1, enum AgentOverlayInfo.State.Status
         error                  :: binary() | iolist() | undefined % = 2
        }).
-endif.

-ifndef('MESOS_STATE_VXLANINFO_PB_H').
-define('MESOS_STATE_VXLANINFO_PB_H', true).
-record(mesos_state_vxlaninfo,
        {vni                    :: non_neg_integer(), % = 1, 32 bits
         vtep_name              :: binary() | iolist(), % = 2
         vtep_ip                :: binary() | iolist(), % = 3
         vtep_mac               :: binary() | iolist() % = 4
        }).
-endif.

-ifndef('MESOS_STATE_BACKENDINFO_PB_H').
-define('MESOS_STATE_BACKENDINFO_PB_H', true).
-record(mesos_state_backendinfo,
        {vxlan                  :: #mesos_state_vxlaninfo{} | undefined % = 1
        }).
-endif.

-ifndef('MESOS_STATE_BRIDGEINFO_PB_H').
-define('MESOS_STATE_BRIDGEINFO_PB_H', true).
-record(mesos_state_bridgeinfo,
        {name                   :: binary() | iolist(), % = 1
         ip                     :: binary() | iolist() % = 2
        }).
-endif.

-ifndef('MESOS_STATE_AGENTOVERLAYINFO_PB_H').
-define('MESOS_STATE_AGENTOVERLAYINFO_PB_H', true).
-record(mesos_state_agentoverlayinfo,
        {info                   :: #mesos_state_overlayinfo{} | undefined, % = 1
         subnet                 :: binary() | iolist() | undefined, % = 2
         mesos_bridge           :: #mesos_state_bridgeinfo{} | undefined, % = 3
         docker_bridge          :: #mesos_state_bridgeinfo{} | undefined, % = 4
         backend                :: #mesos_state_backendinfo{} | undefined, % = 5
         state                  :: #'mesos_state_agentoverlayinfo.state'{} | undefined % = 6
        }).
-endif.

-ifndef('MESOS_STATE_AGENTINFO_PB_H').
-define('MESOS_STATE_AGENTINFO_PB_H', true).
-record(mesos_state_agentinfo,
        {ip                     :: binary() | iolist(), % = 1
         overlays = []          :: [#mesos_state_agentoverlayinfo{}] % = 2
        }).
-endif.

-ifndef('MESOS_STATE_STATE_PB_H').
-define('MESOS_STATE_STATE_PB_H', true).
-record(mesos_state_state,
        {network                :: #mesos_state_networkconfig{} | undefined, % = 1
         agents = []            :: [#mesos_state_agentinfo{}] % = 2
        }).
-endif.

-endif.
